thirdweb-dev/dashboard

components/homepage/LandingMenu.tsx
constants/currencies.ts

WETH is the most popular ERC-20 token so it's good to have it on the currency list, some users have requested this

Add WETH to Mumbai currency list

---

pages/[wallet]/[network]/new/[type]/[contractType].tsx

Quorum doesn't accept decimals, only a number between 0-100.

Fix vote contract deployment

---

contract-ui/tabs/nfts/components/mint-button.tsx
contract-ui/tabs/nfts/page.tsx

Not sure about the implementation here.
Right now we're checking ERC721/ERC1155 for the tab and giving the user a checkmark, but we actually care about Enumerable for that tab to show anything.
might be worth showing the tab always but without the checkmark? or tab always but checkmark when enumerable?
for now, I left it so it shows the tab with checkmark when ERC721/ERC1155 but it tells you that you need to implement enumerable, also hides the Mint button if the contract is not mintable

Enumerable check

---

contract-ui/tabs/overview/cards/custom-contract-code.tsx
utils/network.ts

This fixes a wrong suggestion of chainName on custom contracts
We should also merge this one: https://github.com/thirdweb-dev/typescript-sdk/pull/527 on the ts sdk that's not using the same mapping as in our dashboard

Fix code suggestion on custom contracts

---

contract-ui/tabs/code/components/code-overview.tsx

This works fine in the @dev version of the SDK, would be good to make it a stable build.
Not super critical to do before merging since current state is broken but would be good.

Fix useContractCall code snippet

---

contract-ui/tabs/sources/page.tsx

if already verified, it'll tell you once you click the button
(we want this to verify our own implementations we deploy)
as a next step we can fetch verification status first and show a "already verified" label instead

always show verify on etherscan button

---

pages/api/verify.ts

Context:
Adding support for contract verification for contracts that use `thirdweb deploy` instead of `thirdweb release`.
It's currently using the solc metadata bytes to identify end of the contract bytecode, then locate the constructor params.
To test:
1. write a smart contracts
2. `npx thirdweb@latest deploy`
3. sources  -> verify

Support etherscan verification for un-released contracts

---

components/contract-tabs/code/CodeSegment.tsx
components/contract-tabs/code/ContractCode.tsx
components/contract-tabs/code/types.ts
contract-ui/tabs/code/components/code-overview.tsx

This feels good enough for now, we _could_ have the Web3Button appear below the code, but will need passing more props to the CodeSegment component which I don't think it's worth.
I think this helps with discovery and the link to doc completes the flow.

Add Web3Button option to code tab

---

pages/_app.tsx

Google didn't take our metadesc because I wrote "build, launch, and manage web3 apps..." - needs to include copy on the homepage so changed this to "build web3 apps easily" & will be more likely to use it.
"Build, launch, manage" is better messaging & we can switch back to it once we update homepage copy (there have been branding discussions here)

Updated metadescription

---

pages/index.tsx

Adjusted padding to avoid huge dead space on mobile.
Before -> https://www.loom.com/share/0094c11e6b3a4f3c8784d9cd282c28f5
<hr />
After -> https://www.loom.com/share/f2f1768f3d12440f8817952208f713c4

Adjust top padding to avoid huge dead space on mobile

---

contract-ui/tabs/listings/components/list-form.tsx
contract-ui/tabs/listings/components/listing-drawer.tsx
core-ui/nft-drawer/nft-drawer.tsx

We don't currently return token standard for listing asset, what we call "type" is listing type (direct or auction), fixed it to show that and also fixed not showing owner for erc1155 on general NFT drawer which was pending

Improve marketplace drawer

---

components/homepage/sections/NewsletterSection.tsx

The newsletter form only has a single input element as shown below
* using `react-hook-form` for handling a single input is not necessary 
* removing `react-hook-form` from the newsletter will reduce JS bundle size by a 22kB on any page that use it (unless of course, that page has other components using `react-hook-form` )
---
* `react-hook-form` replaced with idiomatic code for handling submission - Yes, Its a bit verbose but reduces a lot of code in the final bundle size
* functionality remains the same ( prevent submission on invalid email, preventDefault for submit event, clear input after submission, loading state indicator )
<br/>

optimize-newsletter: drop react-hook-form

---

components/homepage/sections/CLISection.tsx
components/product-pages/homepage/HomepageSection.tsx

Hi @jnsdls,
This PR implements the changes I suggested in https://github.com/thirdweb-dev/dashboard/issues/703#issuecomment-1340070587 
With this code change, The issue of Aurora being too small on a regular desktop screen is fixed and its size goes back to what it was originally before we replaced the CSS blur with the Aurora image, and looks good across all widths
I've also added a missing Aurora Image in CLISection 
<br/>
Problem: The Aurora looks a bit odd and out of place because of its smaller size
<br/>
<br/>
---
<br/>
<br/>
problem: The UI looks too dark because it's missing an aurora image on top ( This section used to be properly lit up before we changed CSS blur to image - see this [preview](https://thirdweb-www-git-imgbot-thirdweb.vercel.app/) )

Landing Page: Fix Aurora Images

---

core-ui/update-notice/update-notice.tsx

PR fixes the below-shown error thrown by [emotion](https://github.com/emotion-js/emotion) in dev when clicking on the "Claim conditions" tab as shown below:

Fix emotion's string not allowed as css prop error in UpdateNotice

---

components/product-pages/common/ProductCard.tsx

Fixes https://github.com/thirdweb-dev/dashboard/issues/747 
* Change `<p>` to `<div>` by Using `<Box>` instead of `<Text>` as a container of `props.children` for `ProductCard` component to fix hydration error in `/sdk` page and future hydration errors as well
* Added `color` and `lineHeight` styles to maintain styles as it was earlier

Fix Hydration Error in /sdk page by fixing ProductCard

---

components/layout/app-shell/index.tsx

Issue was that Logo in Dashboard points to /explore when the wallet is not connected
PR makes it so that Logo always points to /dashboard

Fix Logo Link in AppShell when wallet is not connected

---

pages/contracts/deploy/[contractId].tsx

`/contracts/deploy` page is using a different icon for extensions compared to `/dashboard`
This PR Fixes that and makes the icon for extensions the same everywhere

/contracts/deploy page: Use the same icon for extensions used in dashboard

---

contract-ui/tabs/settings/components/platform-fees.tsx
contract-ui/tabs/settings/components/royalties.tsx

https://user-images.githubusercontent.com/22043396/212348189-690514ca-739f-401f-9847-308f73a3e7a2.mov
* "Update Royalties Settings" button stays disabled even when the Royalty percentage input is updated
* "Update Platform Fee Settings" button stays disabled even when the Royalty percentage input is updated
https://user-images.githubusercontent.com/22043396/212348670-16ca1d61-9b78-4597-90c8-63e1308db319.mov

SettingsRoyalties: Mark Percentage dirty when value is changed

---

contract-ui/tabs/claim-conditions/components/claim-conditions-form/Inputs/ClaimerSelection.tsx

* "See Snapshot button" is always enabled for non-admin user
* "Edit Snapshot button" is always enabled for admin user
https://user-images.githubusercontent.com/22043396/212715976-e51569f5-6253-4145-8c81-a73595af7e39.mov
* "See Snapshot button" is always enabled for non-admin user
* "Edit Snapshot button" is always disabled when form data is being fetched for the admin user
https://user-images.githubusercontent.com/22043396/212717221-1baf1997-75f8-4330-89bf-702b85d93585.mov

ClaimCondition Form: Disable snapshot edit button when form is disabled

---

components/contract-components/contract-deploy-form/built-in-contract.tsx

`<BuiltinContractForm/>` is rendered one after another indefinitely because of the `useDeploy` hook

Fix Infinite rendering issue of <BuiltinContractForm/>

---

tw-components/code-block.tsx

Fix code snippet not visible on light mode

---

components/contract-components/released-contract/markdown-renderer.tsx

Fixes this issue: 
https://thirdweb.com/thirdweb.eth/TokenStake

Fix overflow in markdown renderer caused by inline code

---

pages/[profileAddress]/index.tsx

example: https://thirdweb.com/foo shows spinner forever instead of redirecting to a different page
valid routes with one segment: 
https://thirdweb.com/jns.eth
https://thirdweb.com/0x1F846F6DAE38E1C88D71EAA191760B15f38B7A37
I'm redirecting to 404 now, but we can also redirect to /explore or something ..

Fix invalid route with one segment showing spinner indefinitely

---

program-ui/nft/components/table.tsx

This Error noticed on https://thirdweb.com/solana/D6FiWCSgnC26RP1AtZudChVfW3KfWasehkn1kCyip7V

Fix Solana NFT table crash when token Id is number

---

pages/publish.tsx

Updated the guides section to use Publish instead of Release
Before:
After:

use "publish" instead of "release"

---

utils/errorParser.tsx

This would trigger if trying to switch to a network with an invalid RPC.

Fix application error

---

components/selects/NetworkSelectorButton.tsx

https://user-images.githubusercontent.com/22043396/230973521-1842fb20-3605-4382-816c-ea1033c26af1.mov
`onSwitch()` prop of `NetworkSelectorButton` not called when switching the network from wallet app/extension

Fix Network popover showing wrong network when switching via wallet app

---

components/app-layouts/providers.tsx

Root cause 
* passing chainId as activeChain which is not one of supportedChains or defaultChains 
* this was fine earlier - but now SDK throws an error if given chainId is not one of supportedChains in react-core
* this was done - because that's invalid - react-core would silently fail to resolve the chainId to chain object and use Ethereum
* now we throw an error to let the users of SDK know that that's invalid
* so need to pass entire chain object

Fix broken pages on non-default chains

---

components/notices/PrivacyNotice.tsx

why? - https://linear.app/thirdweb/issue/PLAT-985#comment-d0cf3796
PrivacyNotice Modal's focus trapping does not allow selecting network in Safe wallet

Turn off focus trap on PrivacyNotice modal

---

contract-ui/tabs/sources/page.tsx

I'm currently fixing this issue only but 
we should enable `"noUncheckedIndexedAccess": true` and fix all the issues like this 
https://linear.app/thirdweb/issue/FTD-1877/fix-unchecked-indexes

Fix error on /sources for chain with empty explorers array

---

pages/_app.tsx

Disable font ligature to prevent showing of 'x' in the account address in two different ways as shown below
https://rsms.me/inter/

Disable font ligatures

---

pages/api/og/contract.tsx

Fixes https://linear.app/thirdweb/issue/FTD-1950/og-image-for-contract-doesnt-pull-contract-name-correctly

Fix OG image not showing contract with name <=3 characters

---

contract-ui/tabs/nfts/components/table.tsx

For 50 items per page:
Old code:
```
Math.ceil(safeTotalCount.div(50).toNumber()); // 101 -> 2 pages (incorrect)
```
New code:
```
Math.ceil(safeTotalCount.toNumber() / 50); // 101 items -> 3 pages (correct)
```
You can test with this collection here (it has 101 nfts): https://thirdweb.com/avalanche-fuji/0xAD4A13F5dabFf3A0a2C7d9F6eB8670753a4C6159/nfts

Fix issue #1391

---

components/homepage/sections/ValuesSection.tsx

Add space to the text from the value section of the homepage.

tweak: add space to text

---

components/product-pages/common/GuideShowcase.tsx

Fix GuidesShowcase description alignment

---

components/wallets/ConnectWalletPlayground/PreviewThirdwebProvider.tsx

For some weird reason, setting autoConnect={false} on ThirdwebProvider inside ThirdwebProvider for the playground creates an issue with smart wallet - I'll need to debug this further and fix the root cause in SDK but for now this fixes the issue

Fix Smart Wallet connection in ConnectWallet playground

---

components/engine/configuration/engine-wallet-config.tsx

Use radio buttons instead of buttons for selecting the wallet type in config.
**Before**
**After**

chore: Radio buttons for wallet type select

---

@3rdweb-sdk/react/hooks/useEngine.ts
components/engine/overview/engine-overview.tsx

Adds autoUpdate button in the transactions table in Engine.
Defaults to false. If enabled, refetches txn list from Engine every 2 seconds.

feat: autoupdate txn table toggle

---

middleware.ts

- we have a narrow set of statically know-able paths that we need to run through middleware
- this changes the middleware matcher from *broadly* matching on every request to instead matching only those set of paths

refactor: simplify middleware route matching

---

data/explore.ts

Deprecating it because we often receive support questions for it, and it often doesn't meet the user's needs. Currently, it causes more confusion than it provides usefulness

Deprecate SignatureDrop

---

@3rdweb-sdk/react/hooks/usePayments.ts
components/payments/enable-payments-button.tsx

**Bug Analysis**
- In payments, thirdweb contract is registered as custom contract
- Occurs when current wallet chainId is different from the chainId of the payments contract being registered (easily replicated for this scenario)
- Contract ABI is not found for { chainId, contractAddress }, so thirdweb type is not detected
- Incorrect flow is used when adding a checkout link due to the wrong contract type
**Changes**
- Bug Fix: Pull contract abi for the payments { chainId, contractAddress } being registered
- Add contract name to the payments contract being registered
**Tests**

Payments Bug Fix: Register Wrong Contract Type

---

components/engine/overview/transactions-table.tsx

Add a drawer that shows details Engine txns from the transactions table.

feat: add Engine txn details drawer

---

components/storage/your-files.tsx

Related: https://github.com/thirdweb-dev/dashboard/pull/2109
Old:
```
(data?: PinnedFilesResponse) => data?.result.count || 0,
```
New:
```
(data?: PinnedFilesResponse) => data?.result?.count || 0,
```
Error:

Fallback value for total pinned files
