components/contract-tabs/permissions/ContractPermission.tsx, constants/mappings.ts
Also update some descriptions
https://linear.app/thirdweb/issue/FTD-118/rename-minter-role-to-creator-role-on-drops
=> Rename minter to creator

components/batch-upload/BatchTable.tsx, components/batch-upload/EditionDropBatchUpload.tsx, components/batch-upload/NftDropBatchUpload.tsx
Fixes so it shows the correct token id when uploading a second batch
=> Correct tokenId batch upload

@3rdweb-sdk/react/components/connect-wallet/index.tsx, components/app-layouts/app.tsx, components/layout/app-shell/index.tsx, pages/[wallet]/index.tsx, pages/start.tsx
- Emit event on wallet_connected with connector
- Register connector
- Register balance/chainId every time it changes
- Disable "Connect Wallet" navbar button when seeing the big middle conect wallet button
- Redirect to /contracts if on /dashboard and no contracts found
=> Small ftux changes

components/batch-upload/AirdropUpload.tsx, components/batch-upload/SnapshotUpload.tsx
Also, add clarification that repeated addresses will get removed
=> Trim quantity/maxClaimable

components/contract-components/contract-release-form/index.tsx, components/contract-components/released-contract/markdown-renderer.tsx
=> fix redirecting to ENS release link

contract-ui/tabs/nfts/components/lazy-mint-button.tsx, contract-ui/tabs/nfts/components/mint-form.tsx, contract-ui/tabs/nfts/page.tsx
Also changed the order of the "No enumerable extension enabled" to still show the buttons even if you don't extend that extension.
=> Add single lazy mint

components/contract-components/contract-deploy-form/built-in-contract.tsx, components/contract-components/contract-deploy-form/custom-contract.tsx
Fixes FTD-666 (also the comment)
=> Disable rinkeby on custom contracts dpeloy

components/contract-tabs/code/ContractCode.tsx, contract-ui/tabs/code/components/code-overview.tsx
=> Code tab fixes

contract-ui/tabs/nfts/components/airdrop-tab.tsx, contract-ui/tabs/nfts/components/mint-form.tsx, contract-ui/tabs/nfts/components/select-reveal.tsx, contract-ui/tabs/nfts/components/transfer-tab.tsx, contract-ui/tabs/permissions/components/index.tsx, contract-ui/tabs/settings/components/metadata.tsx, contract-ui/tabs/settings/components/platform-fees.tsx, contract-ui/tabs/settings/components/primary-sale.tsx, contract-ui/tabs/settings/components/royalties.tsx, contract-ui/tabs/tokens/components/airdrop-form.tsx, contract-ui/tabs/tokens/components/mint-form.tsx, contract-ui/tabs/tokens/components/transfer-form.tsx
Started doing some dashboard and this made more sense to me
=> Standarize tracking

components/batch-upload/AirdropUpload.tsx, components/batch-upload/SnapshotUpload.tsx
We need to make these two components one, they share all the logic.
Also, we can add a button to remove all addresses for the user, will make a ticket but want to fix the bug first.
=> Disable "Next" button when invalid addresses found

pages/[networkOrAddress]/index.tsx
This work, open to feedback on wording.
=> Add SEO to releaser page

components/contract-functions/contract-function.tsx
Hate this a bit but it works :D
=> Fix highlighting on contract explorer

components/contract-components/released-contract/index.tsx, components/contract-components/shared/sources-accordion.tsx, components/contract-components/shared/sources-panel.tsx, contract-ui/tabs/sources/page.tsx
Also stop filtering dependencies
=> Add upsell button and move ABI to accordion

components/contract-functions/contract-functions.tsx, components/product-pages/common/Hero.tsx, contract-ui/tabs/overview/page.tsx
Still need to fix the long loading but this is a patch
=> Fix contract explorer skeleton

components/contract-functions/interactive-abi-function.tsx
Also functions with no parameters gets auto-run.
=> Read functions not requiring connect wallet/switch network

components/contract-pages/table/table-columns/cells/media-cell.tsx, components/custom-contract/contract-header/contract-metadata.tsx, next.config.js
=> fix various small bugs

contract-ui/tabs/permissions/page.tsx, contract-ui/tabs/settings/components/detected-state.tsx, pages/index.tsx
=> Fix broken portal links

contract-ui/tabs/embed/components/embed-setup.tsx, contract-ui/tabs/nfts/components/select-reveal.tsx, contract-ui/tabs/settings/components/metadata.tsx, contract-ui/tabs/settings/components/platform-fees.tsx, contract-ui/tabs/settings/components/primary-sale.tsx, contract-ui/tabs/settings/components/royalties.tsx
Also made the clickable area for the batch upload issue just the text instead of the whole width
Also update embeds CID
=> Fix network switching not showing

components/contract-functions/contract-function.tsx, components/contract-functions/interactive-abi-function.tsx, sentry.config.js, utils/batch.ts
=> Sentry improvements

contract-ui/tabs/claim-conditions/components/snapshot-upload.tsx, contract-ui/tabs/nfts/components/airdrop-upload.tsx, contract-ui/tabs/nfts/components/batch-lazy-mint.tsx, contract-ui/tabs/nfts/components/upload-step.tsx
Also added some style changes to airdrop/snapshot upload
=> Return error if CSV/JSON don't have a name column

contract-ui/tabs/nfts/components/batch-lazy-mint.tsx, utils/batch.ts
We don't need to check length, if length is 0 after having adding a JSON we know the JSON was invalid.
=> Add error handling for invalid JSONs

pages/contracts/new/pre-built/[type]/[contractType].tsx
=> Add check for prebuilt deploy page

contract-ui/tabs/nfts/components/batch-lazy-mint-button.tsx, core-ui/batch-upload/batch-lazy-mint.tsx, core-ui/batch-upload/batch-table.tsx, core-ui/batch-upload/upload-step.tsx, program-ui/nft/nft-drop-panel.tsx
Revert back to old styles and fix typo. 
I don't think we can have this:
=> Revert batch upload styles

contract-ui/tabs/settings/components/detected-state.tsx, pages/index.tsx
Pushing a fix for the links, now users would not be annoyed to see a page not found error. 🌈
=> Fixed Broken ContractKit Links

contract-ui/tabs/embed/components/embed-setup.tsx
I hate this but Chakra changed how useClipboard works in this PR https://github.com/chakra-ui/chakra-ui/pull/6763/files, basically making it so you now have setValue, for some reason it doesn't take refresh on rerenders now.
I also added a basic isValidURL function to avoid SDK errors when writing the openzeppelin relayer and a useMemo to the embedCode gen
=> useEffect for setValue

pages/_app.tsx
Our metas still include "drop NFTs with no code" and "no-code for NFT artists" - needed to change to reflect our positioning today!
Lmk if this needs edits (the code i changed) & i'll make them asap
=> Change homepage metatitle & description

.eslintrc.js
=> Add linting rule for no console.logs

pages/network/solana.tsx
Updating the Solana network page meta title to H1 from H2.
=> Change H2 --> H1

components/contract-components/contract-deploy-form/built-in-contract.tsx, components/contract-components/contract-deploy-form/index.tsx, constants/mappings.ts, contract-ui/tabs/claim-conditions/components/claim-conditions.tsx
thoughts on implementation @jnsdls ?
Will also like to testjam it
=> Add OSRoyaltyToPrebuilt mapping

pages/index.tsx
PR so Yan can add comments to Vercel
=> Landing page improvements

components/contract-functions/interactive-abi-function.tsx
I think this is a good middleground until we have some sort of JSON parsing for our Media Renderer
=> Add link to open ipfs hashes on gateway

pages/_app.tsx
Fixes https://github.com/thirdweb-dev/dashboard/issues/759 
| page | Before: render count | After: render count | 
| --- | --- | --- |
| home page | 3 | 1 | 
| dashboard | 2 |  1 |
| product pages | 2 |  1 | 
| solution pages | 2 |  1 | 
| contract details pages | 2 |  1 | 
| explore page | 2 |  1 |
=> Fix multiple re-renders of Entire App 🎉

pages/[networkOrAddress]/[...catchAll].tsx
Currently dashboard uses the `/<network-name>/<contract_address>` path scheme
Add support for `/<chain_id>/<contract_address>` as well 
For example: `/80001/<contract-address>` should open the same page as `/mumbai/<contract-address>` ( mumbai's chain id is 80001 )
=> Support network chain-id path in Dashboard

pages/_app.tsx
Fixes https://github.com/thirdweb-dev/dashboard/issues/758
=> Fix font loading issue

pages/[networkOrAddress]/[...catchAll].tsx
https://user-images.githubusercontent.com/22043396/214010848-be70dd6c-cb9d-43a9-b180-7d6e9d8e6d6d.mov
https://user-images.githubusercontent.com/22043396/214011618-4ae09537-6eb1-4453-8403-ec6305242803.mov
=> Add Loading Spinner to CatchAll routes fallback, and show 404 on Release page error

pages/hackathon/readyplayer3.tsx
updating dev post submission workshop from 1/31 --> 2/6
=> Updated Dev Post Submission Date

pages/evm/[...paths].tsx
Refer to video to see what's the issue and how it's fixed :
https://user-images.githubusercontent.com/22043396/218829804-6cd463af-11c1-41cb-ad28-0cfce1125dbb.mov
=> Fix network config form not removed when custom network with required chain id configured

program-ui/layout/tab-router.tsx
Issue: 
* no active indicator
* wrong tab href 
https://user-images.githubusercontent.com/22043396/218984417-28a3253f-cecd-4dae-bbe5-f05b650b2bfe.mov
=> Fix Solana Program Tabs

components/cmd-k-search/index.tsx, components/contract-components/contract-deploy-form/built-in-contract.tsx, components/contract-components/contract-deploy-form/custom-contract.tsx, contract-ui/components/solidity-inputs/helpers.ts, contract-ui/components/solidity-inputs/index.tsx, contract-ui/tabs/claim-conditions/components/snapshot-upload.tsx, contract-ui/tabs/code/components/code-overview.tsx, contract-ui/tabs/nfts/components/airdrop-upload.tsx, contract-ui/tabs/nfts/components/mint-form.tsx, contract-ui/tabs/sources/page.tsx, lib/ens.ts, middleware.ts, pages/[profileAddress]/index.tsx, pages/api/ens/[ens].ts, pages/api/og/contract.tsx
=> auto-verify where possible

pages/contracts/deploy/[contractId].tsx
=> Update Extension icon on /contracts/deploy

pages/chains.tsx
=> Fix overflow on /chains

pages/chain/[chainSlug].tsx
=> Fix button alignment on /[chainSlug]

pages/chain/[chainSlug].tsx
=> Fix /[chainSlug] UI issue on safari mobile

components/contract-components/contract-deploy-form/custom-contract.tsx
This reverts commit 967b1592b3e1e35a1f7bf5dd190838f37927f851.
=> Revert "enable anyEVM deploys for Airdrop/Staking (#968)"

components/homepage/sections/key-features/BuildSection.tsx
=> landing page updates

components/notices/AnnouncementBanner.tsx, pages/learn/index.tsx
=> Updates banner to learn announcement

@3rdweb-sdk/react/components/connect-wallet/index.tsx, components/app-layouts/app.tsx, components/configure-networks/ConfigureNetworkModal.tsx, components/configure-networks/ConfigureNetworks.tsx, contexts/configured-chains.tsx, hooks/chains/configureChains.ts, hooks/chains/recentlyUsedChains.ts, pages/dashboard/index.tsx, pages/evm/[...paths].tsx
Fixes https://linear.app/thirdweb/issue/FTD-1648#comment-84e8ecf3
and some code cleanup
Fix FTUX flash - Remove the timeout hack, use the `useConnectionStatus()`
=> network config improvements, Fix FTUX flash

components/contract-components/contract-deploy-form/platform-fee-fieldset.tsx, components/contract-components/contract-publish-form/factory-fieldset.tsx, components/contract-components/contract-publish-form/index.tsx, components/contract-components/contract-publish-form/proxy-fieldset.tsx
Fixes
* https://thirdwebdev.slack.com/archives/C04EJJW373K/p1681241108024879
* https://thirdwebdev.slack.com/archives/C04EJJW373K/p1681240852520149
=> Fix publish form, Platform fees accordion

components/explore/contract-card/index.tsx
Removed unwanted `<ClientOnly/>` wrapper which was added to fix Hydration error, but that doesn't exist anymore.
=> Fix /explore page SSR

components/notices/AnnouncementBanner.tsx
not sure if i set the local storage correctly or tracking label correctly, lmk
we can add the community CTA back once airdrop is over!
=> Update Announcement Banner to Bear Market Builders

@3rdweb-sdk/react/hooks/useApi.ts, components/app-layouts/providers.tsx, constants/urls.ts
- This PR updates the REST paths to manage API keys
=> Use new paths for API keys

pages/about.tsx
=> chore: add missing twitter handle

components/contract-components/contract-table/cells/name.tsx
=> fix: align name in the deployed contracts table

contract-ui/tabs/nfts/components/table.tsx
=> hotfix: fit desc in contracts nft table

pages/solutions/commerce.tsx, pages/solutions/gaming.tsx, pages/solutions/minting.tsx
Metadata for CommerceKit, GamingKit, Minting API solutions pages
=> Solutions SEO metadata

pages/chainlist.tsx
Before:
https://www.webpagetest.org/breakdownTimeline.php?test=230706_AiDcJP_7M3&run=1
After: 
https://www.webpagetest.org/breakdownTimeline.php?test=230706_BiDcV6_7E3&run=3
=> Improve /chainlist perf

pages/api/luma-events.ts, pages/events.tsx
The main problem was that /events page was showing the skeleton when API returned no events
* changed skeleton to loading spinner - skeleton looks weird
* use react-query instead of useEffect fetch
* show no events found message
* show error loading events message
* return 500 when luma endpoint response not ok
=> Fix /events page

@3rdweb-sdk/react/hooks/useApi.ts, components/settings/ApiKeyTable/Alerts.tsx, components/settings/ApiKeyTable/Details.tsx, components/settings/ApiKeyTable/KeyForm.tsx, components/settings/ApiKeyTable/validations.test.ts, components/settings/ApiKeyTable/validations.ts, pages/dashboard/settings/api-keys.tsx, utils/string.ts
- validate key name uniqueness
- fix enter on submit refreshing page
- polish copy
=> chore: api keys polish

@3rdweb-sdk/react/cache-keys.ts, contract-ui/tabs/account/components/account-balance.tsx, contract-ui/tabs/account/components/nfts-owned.tsx
page to test: `/optimism-goerli/0x8779407A011687570659Bb2094744f5AE36505C2/account`
=> Add deposit button to smart wallet account tab

package.json, yarn.lock
=> Enable dynamic contract deployment with any evm flow

pages/templates.tsx
=> correct link for marketplace template

components/wallets/ConnectWalletWithPreview.tsx, pages/dashboard/index.tsx
* Fix Grammar in ConnectWallet preview
* Fix Get Started / FTUX not rendering anything when wallet is connecting
=> Minor Fixes 

components/settings/ApiKeyTable/index.tsx
=> chore: add last accessed at to keys

@3rdweb-sdk/react/hooks/useApi.ts, components/settings/Account/Usage.tsx, components/settings/Account/UsageCard.tsx, utils/number.ts
=> feat: add storage usage and limits

@3rdweb-sdk/react/hooks/useApi.ts, components/layout/app-shell/index.tsx, components/settings/Account/BillingAlert.tsx, components/settings/Account/Usage.tsx, components/settings/Account/UsageCard.tsx, components/settings/ApiKeyTable/Alerts.tsx, pages/dashboard/settings/api-keys.tsx, utils/number.ts
=> feat: update usage cards for all services

@3rdweb-sdk/react/hooks/useApi.ts, components/onboarding/index.tsx, components/settings/Account/AccountForm.tsx, components/settings/Account/Notifications.tsx, core-ui/sidebar/settings.tsx, page-id.ts, pages/api/email-signup.ts, pages/dashboard/settings/billing.tsx, pages/dashboard/settings/notifications.tsx, pages/dashboard/settings/usage.tsx
=> feat: notification preferences

data/explore.ts, pages/solutions/loyalty.tsx
=> feat: add loyalty to explore

@3rdweb-sdk/react/hooks/useApi.ts, components/settings/Account/BillingAlert.tsx, pages/dashboard/settings/billing.tsx
=> feat: show rate limit alerts

components/footer/Footer.tsx, components/footer/footerLinks.tsx, components/product-pages/common/nav/DesktopMenu.tsx, components/product-pages/common/nav/HoverMenu.tsx, components/product-pages/common/nav/MobileMenu.tsx, components/product-pages/common/nav/NavCard.tsx, components/product-pages/common/nav/NestedHoverMenu.tsx, components/product-pages/common/nav/ProductNavCard.tsx, components/product-pages/common/nav/data.ts, components/product-pages/common/nav/types.ts, contract-ui/tabs/overview/components/BuildYourApp.tsx
=> feat: landing developer menu

components/onboarding/SignIn.tsx, components/product-pages/common/nav/DesktopMenu.tsx, components/product-pages/common/nav/HoverMenu.tsx, components/product-pages/common/nav/MobileMenu.tsx, components/product-pages/common/nav/NestedHoverMenu.tsx
=> fix: dynamic main nav positioning

@3rdweb-sdk/react/hooks/useApi.ts
=> fix: useAddress for caching api keys & account

@3rdweb-sdk/react/hooks/useApi.ts, components/onboarding/index.tsx, components/settings/Account/BillingAlert.tsx, components/settings/Account/ManageBillingButton.tsx, pages/dashboard/settings/billing.tsx
=> feat: support ach + payment verification

@3rdweb-sdk/react/hooks/useApi.ts, components/onboarding/ConfirmEmail.tsx, components/onboarding/General.tsx, components/onboarding/PaymentForm.tsx, components/onboarding/index.tsx, components/settings/Account/AccountForm.tsx, components/settings/Account/validations.ts
=> chore: email is now required

@3rdweb-sdk/react/hooks/useApi.ts, components/onboarding/Billing.tsx, components/onboarding/ConfirmEmail.tsx, components/onboarding/PaymentForm.tsx, components/onboarding/index.tsx, utils/regex.ts
=> feat: resend email confirmation

components/onboarding/index.tsx, pages/dashboard/settings/billing.tsx
=> chore: fix billing analytics n payment redirect cleanup

@3rdweb-sdk/react/hooks/useApi.ts, components/settings/Account/AccountForm.tsx
This reverts commit 7d5544c80555d60c1c5a60bdaeef0104007068a9.
=> Revert "tmp: account form error debug (#1915)"

@3rdweb-sdk/react/hooks/useEngine.ts, components/engine/overview/backend-wallets-table.tsx, components/engine/overview/engine-overview.tsx, components/engine/permissions/access-tokens-table.tsx, components/engine/permissions/add-admin-button.tsx, components/engine/permissions/admins-table.tsx, components/engine/permissions/permissions-access-tokens.tsx, components/engine/permissions/permissions-admin.tsx, components/shared/TWTable.tsx
- Adds the ability to view/update labels in Engine (backend wallet, admin, access token)
- Adds an edit component to TWTable
=> feat: Add read/update labels for Engine tables

.github/workflows/mirror-branches.yml, @3rdweb-sdk/react/hooks/useImportContract.ts, components/wallets/ConnectWalletPlayground/PreviewThirdwebProvider.tsx, components/wallets/ConnectWalletPlayground/usePlaygroundWallets.tsx, constants/rpc.ts, contexts/configured-chains.tsx, lib/rpc.ts, next.config.js, sentry.client.config.js
Replace most of the reference **staging** services to **dev** services.
Use **dev** infra on development dashboard build
=> Support dev env

components/settings/ApiKeys/Edit/Services.tsx, components/settings/ApiKeys/validations.ts
This reverts commit 779bbfc9b45b730a0a0f554b44e2ea4f0b16cd34.
=> Revert "Allows empty image urls. Defaults to thirdweb (#1996)"

components/payments/settings/kyb-file-uploader.tsx
**Changes**
- allow pdf upload
**Tests**
=> Payments KYB: add pdf upload

components/payments/settings/payment-webhooks.tsx, components/payments/settings/payments-webhooks-create-webhook-button.tsx
**Changes**
- payments webhooks create form error on duplicate webhook
**Tests**
=> Payments Webhooks Test Jam Items [READY]

components/payments/settings/payment-settings-kyc.tsx, contract-ui/tabs/payments/components/create-update-checkout-button.tsx, contract-ui/tabs/payments/components/mint-method-input.tsx, contract-ui/tabs/payments/components/preview-button.tsx, graphql/generated_types.ts, graphql/schema.json
fixes PROD-442, PROD-441, PROD-440, PROD-439
=> chore: polish checkout creation flow

components/shared/CurrencySelector.tsx, contract-ui/tabs/payments/components/create-update-checkout-button.tsx, contract-ui/tabs/payments/components/mint-method-input.tsx
=> fix: checkout link mint func select, form reset, key

components/payments/contracts/payment-contracts-table.tsx, components/payments/enable-payments-button.tsx, contract-ui/tabs/payments/components/create-update-checkout-button.tsx, contract-ui/tabs/payments/components/payments-analytics.tsx
=> chore: check for nfts/claims on checkout link create

contract-ui/tabs/payments/components/create-update-checkout-button.tsx
**Changes**
- fix bug where create checkout next button is disabled due to form not updating within useMemo
=> Payments: Create Checkout Bug Fix

components/layout/app-shell/index.tsx, contract-ui/hooks/useRouteConfig.tsx
Merge this PR when we're ready to have Payments launched for all developers
=> Launch Payments for all users

contract-ui/tabs/payments/components/create-update-checkout-button.tsx, contract-ui/tabs/payments/components/preview-button.tsx
**Changes**
- convert button branding to correct values
**Tests**
=> Payments Bug Fix: create checkout button branding

@3rdweb-sdk/react/hooks/usePayments.ts
**Changes**
- We should only query and display the checkouts that haven't been deleted
**Tests**
=> Payments Bug Fix: showing deleted checkouts

contract-ui/tabs/payments/components/create-update-checkout-button.tsx
**Changes**
- remove custom branding
- rearrange checkout creation items
**Tests**
=> Payments: remove checkout custom branding

contract-ui/tabs/nfts/components/table.tsx
Test link: https://thirdweb.com/polygon/0xA1972ee3DfAff51146A291671fFc6693DC9bB3B4
Before: 
After:
=> Add text overflow to NFT table

@3rdweb-sdk/react/hooks/useApi.ts, components/settings/Account/BillingAlert.tsx, components/settings/Account/ManageBillingButton.tsx, pages/dashboard/settings/billing.tsx
=> chore: handle payment failure attempt

components/engine/create-engine-instance.tsx, components/engine/engine-list.tsx, components/engine/import-engine-instance.tsx, components/engine/no-connected-wallet.tsx
- Separates import/create buttons
- Use consistent buttons
=> chore: separate Engine import/create buttons

@3rdweb-sdk/react/hooks/useApi.ts, components/onboarding/ConfirmEmail.tsx, components/onboarding/General.tsx, components/onboarding/LinkWallet.tsx, components/onboarding/index.tsx, components/settings/Account/AccountForm.tsx, components/settings/Account/validations.ts
=> feat: account linking

components/storage/your-files.tsx
https://github.com/thirdweb-dev/dashboard/assets/26052673/23b7baf9-c9e3-43e9-bb33-6149e91c6475
=> Fix typeError for the Unpin dashboard

@3rdweb-sdk/react/hooks/useApi.ts, components/homepage/sections/PricingCard.tsx, components/settings/Account/Billing/Pricing.tsx, components/settings/Account/Billing/index.tsx, pages/dashboard/settings/billing.tsx, utils/date-utils.ts
=> feat: growth trial

components/settings/Account/Billing/ManageButton.tsx
allow to go to the billing portal when status is paymentVerification
fixes MON-121
=> fix: payment method button when verifying

@3rdweb-sdk/react/components/connect-wallet/index.tsx, @3rdweb-sdk/react/hooks/useLoggedInUser.ts, components/homepage/sections/PricingCard.tsx, components/homepage/sections/PricingSection.tsx, components/notices/AnnouncementBanner.tsx, components/onboarding/index.tsx, components/settings/Account/Billing/ConnectWallet.tsx, components/settings/Account/Billing/Pricing.tsx, components/settings/Account/Billing/index.tsx, pages/dashboard/settings/billing.tsx, pages/pricing.tsx
=> chore: growth trial flow

components/onboarding/index.tsx, components/settings/Account/Billing/index.tsx, pages/_app.tsx, pages/dashboard/settings/billing.tsx, pages/pricing.tsx
=> Disable free trial

components/engine/relayer/engine-relayer.tsx
fixed broken link in Engine dashboard
=> fixed relayer link

components/engine/permissions/permissions-access-tokens.tsx, components/engine/permissions/permissions-admin.tsx
broken links in Engine dashboard
=> fixed permissions links on engine dashboard

core-ui/sidebar/detail-page.tsx, graphql/generated_types.ts, graphql/schema.json, yarn.lock
=> FIX: CNCT#142

@3rdweb-sdk/react/hooks/usePayments.ts, contexts/custom-sdk-context.tsx, lib/rpc.ts, pages/chainlist.tsx
=> feat: Add invariant check for input chain

components/notices/AnnouncementBanner.tsx, pages/_app.tsx
Reverts thirdweb-dev/dashboard#2253
=> Revert "Update AnnouncementBanner"
